- hosts: all
  tasks:
    - name: "Deploy1"
      proxmox_kvm:
        api_user     : root@pam
        api_password : itescia
        api_host     : 192.168.80.128
        name         : ta01
        node         : proxmox
        ide          : '{"ide0":"local:iso/ubuntu-18.04.1-live-server-amd64.iso,media=cdrom"}'
        virtio       : '{"scsi0":"Data:32,format=raw"}'
        net          : '{"net0":"virtio,bridge=vmbr0"}'
        cores        : 2
        memory       : 1024
        ostype       : l26


    - name: "Starting VM"
      proxmox_kvm:
        api_user     : root@pam
        api_password : itescia
        api_host     : 192.168.80.128
        name         : ta01
        node         : proxmox1
        state        : started
